[package]
name = "elektrovulkan"
version = "0.1.0"
authors = ["vlad <vladzhukovtirko@gmail.com>"]
edition = "2018"

[dependencies]
winit = "0.19.5"
image = "0.10.4"
ash = "0.31.0"
ash-window = "0.5.0"